
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rodri
 */
public class Ventana2 extends javax.swing.JFrame {

    ArrayList<Entidad> Debiles = new ArrayList<Entidad>(); //Entidades ingresadas, debiles y fuertes
    ArrayList<Entidad> Dependientes = new ArrayList<Entidad>();
    int TamAnt; //Tamaño del arreglo de entidades fuertes
    
    /**
     * Creates new form Ventana2
     */
    DefaultListModel listA = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listB = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listC = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listD = new DefaultListModel(); //Se declara un modelo de lista
    
    public Ventana2() {
        //Se inicializan los elementos de la ventana
        initComponents();
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        btnIntroducir.setEnabled(false);
        btnIntroducir2.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnEliminar2.setEnabled(false);
        btnQuitar.setEnabled(false);
        btnEliminarP3.setEnabled(false);
        lstAtributos.setModel(listA);
        lstProg3.setModel(listB);
        lstEntidades.setModel(listC);
        lstAtributos2.setModel(listD);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtPK = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtAtributos = new javax.swing.JTextField();
        btnIntroducir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jspAtributos = new javax.swing.JScrollPane();
        lstAtributos = new javax.swing.JList<>();
        chbxDerivado = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        cbxEntidad = new javax.swing.JComboBox<>();
        btnAgregarE = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEntidades = new javax.swing.JList<>();
        btnCrear = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jspEntidades3 = new javax.swing.JScrollPane();
        lstProg3 = new javax.swing.JList<>();
        btnEliminarP3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txtAtributos2 = new javax.swing.JTextField();
        btnIntroducir2 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAtributos2 = new javax.swing.JList<>();
        chbxDerivado1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entidad Debil");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Llave Primaria"));

        txtPK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPKKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPK, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos Simples y Derivados"));

        txtAtributos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAtributosKeyTyped(evt);
            }
        });

        btnIntroducir.setText("Introducir Atributo");
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Atributo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lstAtributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributosMouseClicked(evt);
            }
        });
        jspAtributos.setViewportView(lstAtributos);

        chbxDerivado.setText("Derivado");
        chbxDerivado.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAtributos)
                        .addComponent(btnIntroducir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(chbxDerivado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspAtributos)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbxDerivado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidades Fuertes de las que Depende"));

        btnAgregarE.setText("Agregar Entidad");
        btnAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEActionPerformed(evt);
            }
        });

        btnQuitar.setText("Quitar Entidad");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        lstEntidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEntidadesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstEntidades);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxEntidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarE, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cbxEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrear.setText("Crear Entidad");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnSiguiente.setLabel("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidades Creadas"));

        lstProg3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProg3MouseClicked(evt);
            }
        });
        jspEntidades3.setViewportView(lstProg3);

        btnEliminarP3.setText("Eliminar Entidad");
        btnEliminarP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspEntidades3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEliminarP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspEntidades3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarP3)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos de las Relaciones con las Entidades de las que Depende"));

        txtAtributos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAtributos2KeyTyped(evt);
            }
        });

        btnIntroducir2.setText("Introducir Atributo");
        btnIntroducir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducir2ActionPerformed(evt);
            }
        });

        btnEliminar2.setText("Eliminar Atributo");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        lstAtributos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributos2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstAtributos2);

        chbxDerivado1.setText("Derivado");
        chbxDerivado1.setToolTipText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtAtributos2)
                        .addComponent(btnIntroducir2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(btnEliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(chbxDerivado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtAtributos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbxDerivado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Funcion que recibe las entidades fuertes y las agrega a las entidades de esta ventana
    public void Relaciones(ArrayList<Entidad> Fuertes){
        TamAnt = Fuertes.size(); //Se obtiene el tamaño del arreglo de las entidades fuertes
        Debiles = (ArrayList) Fuertes.clone(); // Se clonan las entidades fuertes en las entidades de esta ventana (Debiles)
        llenarcbx(); //Se encarga de llenar el Combobox de Entidades
    }
    
    //Se encarga de llenar el Combobox de Entidades Fuertes
    private void llenarcbx(){
        for(int i=0; i<Debiles.size(); i++)
        {
            cbxEntidad.addItem(Debiles.get(i).Nombre); 
        }
        //Para llenar el combobox (Utilizalo con un for para llenarlo ya que empiza vacio)
    }
    
    //Funcion que crea y extrae los datos de los elementos de la ventana
    private void Crear(){
        
        int i=0;
        ArrayList<Atributo> DebAtribs = new ArrayList<Atributo>();
        
        cbxEntidad.getSelectedItem(); //Regresa la cadena del elemento seleccionado del combobox
        txtNombre.getText(); //Regresa la cadena del campo de Nombre
        txtPK.getText(); //Regresa la cadena del campo de Llave Primaria
        
        Atributo NewPK = new Atributo(txtPK.getText(), true, false);
        DebAtribs.add(NewPK);
        
        for(i=0; i<listA.getSize(); i++)
        {
            System.out.println(""+listA.getElementAt(i)); //Donde listA.getElementAt(i) es la cadena en el espacio 'i' de la lista
            Atributo NewAtrib = new Atributo(listA.getElementAt(i).toString(), false, false);
            DebAtribs.add(NewAtrib);
        }
        
        for(i=0; i<Dependientes.size(); i++)
        {
            Atributo NewPF = new Atributo(Debiles.get(Debiles.indexOf(Dependientes.get(i).Padre)).Atribs.get(0).Nombre, true, true);
            DebAtribs.add(NewPF);
            for(int j=0; j<Dependientes.get(i).Atribs.size(); j++)
            {
                DebAtribs.add(Dependientes.get(i).Atribs.get(j));
            }
        }
        
        Entidad NewEnt = new Entidad(txtNombre.getText(), 'D', 'N', null, false, DebAtribs);
        Debiles.add(NewEnt);
    
    }
    
    //Funcion que elimna la entidad seleccionada en la lista de entidades
    private void Eliminar(int Ind){ //Vas a tener la cadena de la entidad que se quiere eliminar
       Debiles.remove(Debiles.get(Ind+TamAnt));
    }
    
    //Funcion que evalua ciertas condiciones para habilitar o inhabilitar el boton de Crear
    private void permisoCrear(){
    
        //Revisa que los campos de texto de Nombre y Llave primaria no esten vacios ademas de que la lista de atributos no esté vacia
        if(txtNombre.getText().length()==0 || txtPK.getText().length()==0|| listC.isEmpty())
            btnCrear.setEnabled(false); //Habilita el boton de Crear
        else
            btnCrear.setEnabled(true); //Inhabilita el boton de Crear
    
    }
    
    //Accion al presionar el boton "Siguiente"
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        Ventana3 v3 = new Ventana3(); //Se crea un objeto ventana
        
        for(int i=0; i<Debiles.size(); i++)
        {
            System.out.print(Debiles.get(i).Nombre+" = { ");
            for(int j=0; j<Debiles.get(i).Atribs.size(); j++)
            {
                if(Debiles.get(i).Atribs.get(j).Pri && Debiles.get(i).Atribs.get(j).For)
                    System.out.print("°PF°"+Debiles.get(i).Atribs.get(j).Nombre+", ");
                else if(Debiles.get(i).Atribs.get(j).Pri)
                    System.out.print("°P°"+Debiles.get(i).Atribs.get(j).Nombre+", ");
                else
                    System.out.print(Debiles.get(i).Atribs.get(j).Nombre+", ");
            }
            System.out.println("}");
        }
        System.out.println("");
        v3.Relaciones(Debiles);
        
        v3.show(); //Muestra el objeto ventana
        dispose(); //Cierra la ventana actual
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    //Accion al presionar el boton "Introducir Atributo"
    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed
        
        listA.addElement(txtAtributos.getText()); //Agrega el valor en el campo de Atributo a la lista
        txtAtributos.setText(""); //Limpia el campo de Atributo
        chbxDerivado.setSelected(false);
        btnIntroducir.setEnabled(false); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_btnIntroducirActionPerformed

    //Accion al presionar el boton "Eliminar Atributo"
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        listA.removeElementAt(lstAtributos.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar.setEnabled(false); //Inhabilita el boton de Eliminar
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    //Accion al seleccionar un elemento de la lista de atributos
    private void lstAtributosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributosMouseClicked
        
        if(lstAtributos.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar.setEnabled(true); //Habilita el boton de Eliminar
        
    }//GEN-LAST:event_lstAtributosMouseClicked

    //Accion al escribir o borrar caracteres en el campo de Atributos
    private void txtAtributosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtributosKeyTyped
        
        if(txtAtributos.getText().length()==0) //Revisa que el campo de texto de Atributo no esté vacio
            btnIntroducir.setEnabled(false); //Habilita el boton de Introducir
        else
            btnIntroducir.setEnabled(true); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_txtAtributosKeyTyped

    //Accion al escribir o borrar caracteres en el campo de Nombre
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_txtNombreKeyTyped

    //Accion al escribir o borrar caracteres en el campo de Llave Primaria
    private void txtPKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPKKeyTyped
        
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_txtPKKeyTyped

    //Accion al presionar el boton "Crear Entidad"
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        Crear(); //Se llama a la funcion que extraera y creara la entidad con todos los datos
        
        //Se reestablecen los valores originales de los elementos de la ventana
        listB.addElement(txtNombre.getText());
        listA.clear();
        listC.clear();
        listD.clear();
        txtNombre.setText("");
        txtPK.setText("");
        txtAtributos.setText("");
        txtAtributos2.setText("");
        chbxDerivado.setSelected(false);
        chbxDerivado1.setSelected(false);
        cbxEntidad.setSelectedIndex(0);
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_btnCrearActionPerformed

    //Accion al seleccionar un elemento de la lista de entidades
    private void lstProg3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProg3MouseClicked

        if(lstProg3.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminarP3.setEnabled(true); //Habilita el boton de Eliminar Entidad

    }//GEN-LAST:event_lstProg3MouseClicked

    //Accion al presionar el boton "Eliminar Entidad"
    private void btnEliminarP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarP3ActionPerformed

        Eliminar(lstProg3.getSelectedIndex()); //Llama la funcion que borra la entidad de los datos
        listB.removeElementAt(lstProg3.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminarP3.setEnabled(false); //Inhabilita el boton de Eliminar

    }//GEN-LAST:event_btnEliminarP3ActionPerformed

    private void btnAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEActionPerformed
        
        ArrayList<Atributo> DepAtribs = new ArrayList<Atributo>(); //Atributos ingresados
        
        for(int i=0; i<listD.getSize(); i++){
            System.out.println(""+listD.getElementAt(i)); //Donde listA.getElementAt(i) es la cadena en el espacio 'i' de la lista
            Atributo NewAtrib = new Atributo(listD.getElementAt(i).toString(), false, false); //Creamos un atributo por cada elemento puesto en la lista de "Otros atributos"...
            DepAtribs.add(NewAtrib);                                                          //y los agregamos en los atributos ingresados
        }
        
        Entidad NewDep = new Entidad(cbxEntidad.getName(), 'N', 'N', Debiles.get(cbxEntidad.getSelectedIndex()), true, DepAtribs);
        Dependientes.add(NewDep);
        
        listC.addElement(cbxEntidad.getSelectedItem());
        cbxEntidad.setSelectedIndex(0);
        listD.clear();
        permisoCrear();
        
    }//GEN-LAST:event_btnAgregarEActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        
        Dependientes.remove(Dependientes.get(lstEntidades.getSelectedIndex()));
        
        listC.removeElementAt(lstEntidades.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnQuitar.setEnabled(false); //Inhabilita el boton de Eliminar
        
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void lstEntidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEntidadesMouseClicked
        
        if(lstEntidades.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnQuitar.setEnabled(true); //Habilita el boton de Eliminar
        
    }//GEN-LAST:event_lstEntidadesMouseClicked

    private void btnIntroducir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducir2ActionPerformed
        
        listD.addElement(txtAtributos2.getText()); //Agrega el valor en el campo de Atributo a la lista
        txtAtributos2.setText(""); //Limpia el campo de Atributo
        btnIntroducir2.setEnabled(false); //Inhabilita el boton de Introducir
        chbxDerivado1.setSelected(false);
        
    }//GEN-LAST:event_btnIntroducir2ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        
        listD.removeElementAt(lstAtributos2.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar2.setEnabled(false); //Inhabilita el boton de Eliminar
        
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void txtAtributos2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtributos2KeyTyped
        
        if(txtAtributos2.getText().length()==0) //Revisa que el campo de texto de Atributo no esté vacio
            btnIntroducir2.setEnabled(false); //Habilita el boton de Introducir
        else
            btnIntroducir2.setEnabled(true); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_txtAtributos2KeyTyped

    private void lstAtributos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributos2MouseClicked
        
        if(lstAtributos2.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar2.setEnabled(true); //Habilita el boton de Eliminar
        
    }//GEN-LAST:event_lstAtributos2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarE;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnEliminarP3;
    private javax.swing.JButton btnIntroducir;
    private javax.swing.JButton btnIntroducir2;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbxEntidad;
    private javax.swing.JCheckBox chbxDerivado;
    private javax.swing.JCheckBox chbxDerivado1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jspAtributos;
    private javax.swing.JScrollPane jspEntidades3;
    private javax.swing.JList<String> lstAtributos;
    private javax.swing.JList<String> lstAtributos2;
    private javax.swing.JList<String> lstEntidades;
    private javax.swing.JList<String> lstProg3;
    private javax.swing.JTextField txtAtributos;
    private javax.swing.JTextField txtAtributos2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPK;
    // End of variables declaration//GEN-END:variables
}
