
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rodri
 */
public class Ventana4 extends javax.swing.JFrame {

    ArrayList<Entidad> Entidades = new ArrayList<Entidad>();
    ArrayList<Relacion> Relaciones = new ArrayList<Relacion>();
    ArrayList<Entidad> AtribComp = new ArrayList<Entidad>();
    
    /**
     * Creates new form Ventana4
     */
    
    DefaultListModel listA = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listB = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listC = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listD = new DefaultListModel(); //Se declara un modelo de lista
    
    public Ventana4() {
        //Se inicializan los elementos de la ventana
        initComponents();
        llenarcbx(); //Se encarga de llena los Combobox de Entidades
        rbtn11.setSelected(true);
        btnIntroducir.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCrear.setEnabled(false);
        btnIntroducir2.setEnabled(false);
        btnEliminar2.setEnabled(false);
        btnCrearCom.setEnabled(false);
        btnEliminarP.setEnabled(false);
        btnEliminarP2.setEnabled(false);
        lstAtributos.setModel(listA);
        lstProg.setModel(listB);
        lstAtributos2.setModel(listC);
        lstProg2.setModel(listD);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngCardinalidad = new javax.swing.ButtonGroup();
        btnParticipacion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cbxEntidad1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cbxEntidad2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txtAtributos = new javax.swing.JTextField();
        btnIntroducir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jspAtributos = new javax.swing.JScrollPane();
        lstAtributos = new javax.swing.JList<>();
        chbxDerivado = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        rbtn11 = new javax.swing.JRadioButton();
        rbtn1n = new javax.swing.JRadioButton();
        rbtnn1 = new javax.swing.JRadioButton();
        rbtnnm = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        rbtnpp = new javax.swing.JRadioButton();
        rbtntt = new javax.swing.JRadioButton();
        rbtnpt = new javax.swing.JRadioButton();
        rbtntp = new javax.swing.JRadioButton();
        btnSiguiente = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jspRelaciones = new javax.swing.JScrollPane();
        lstProg = new javax.swing.JList<>();
        btnEliminarP = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtNombreC = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        txtAtributos2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAtributos2 = new javax.swing.JList<>();
        btnIntroducir2 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        btnCrearCom = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProg2 = new javax.swing.JList<>();
        btnEliminarP2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relaciones de Grado <= 2");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidad 1"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidad 2"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos Simples y Derivados de la Relacion"));

        txtAtributos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAtributosKeyTyped(evt);
            }
        });

        btnIntroducir.setText("Introducir Atributo");
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Atributo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lstAtributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributosMouseClicked(evt);
            }
        });
        jspAtributos.setViewportView(lstAtributos);

        chbxDerivado.setText("Derivado");
        chbxDerivado.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIntroducir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(txtAtributos, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(chbxDerivado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbxDerivado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cardinalidad"));

        btngCardinalidad.add(rbtn11);
        rbtn11.setText("1:1");
        rbtn11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtn11StateChanged(evt);
            }
        });

        btngCardinalidad.add(rbtn1n);
        rbtn1n.setText("1:N");

        btngCardinalidad.add(rbtnn1);
        rbtnn1.setText("N:1");

        btngCardinalidad.add(rbtnnm);
        rbtnnm.setText("N:M");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn11)
                    .addComponent(rbtnnm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn1n, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnn1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn11)
                    .addComponent(rbtn1n))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnn1)
                    .addComponent(rbtnnm)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Participacion"));

        btnParticipacion.add(rbtnpp);
        rbtnpp.setText("Parcial - Parcial");

        btnParticipacion.add(rbtntt);
        rbtntt.setText("Total - Total");

        btnParticipacion.add(rbtnpt);
        rbtnpt.setText("Parcial - Total");

        btnParticipacion.add(rbtntp);
        rbtntp.setText("Total - Parcial");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbtnpp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnpt))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbtntt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtntp))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnpp)
                    .addComponent(rbtnpt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtntt)
                    .addComponent(rbtntp)))
        );

        btnSiguiente.setLabel("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear Relacion");
        btnCrear.setToolTipText("");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Relaciones Creadas"));

        lstProg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProgMouseClicked(evt);
            }
        });
        jspRelaciones.setViewportView(lstProg);

        btnEliminarP.setText("Eliminar Relacion");
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspRelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEliminarP, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspRelaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarP)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos Compuestos de la Relacion"));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtNombreC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos que lo Componen"));

        txtAtributos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAtributos2KeyTyped(evt);
            }
        });

        lstAtributos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributos2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstAtributos2);

        btnIntroducir2.setText("Introducir Atributo");
        btnIntroducir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducir2ActionPerformed(evt);
            }
        });

        btnEliminar2.setText("Eliminar Atributo");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAtributos2)
                    .addComponent(btnIntroducir2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnEliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtAtributos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrearCom.setText("Crear Compuesto");
        btnCrearCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearComActionPerformed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos Compuestos Creados"));

        lstProg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProg2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstProg2);

        btnEliminarP2.setText("Eliminar Compuesto");
        btnEliminarP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarP2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearCom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrear)
                                .addGap(37, 37, 37)
                                .addComponent(btnSiguiente))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Relaciones(ArrayList<Entidad> Hijas){
         Entidades = (ArrayList) Hijas.clone();
        llenarcbx(); //Se encarga de llenar el Combobox de Entidades
    }
    
    //Se encarga de llenar el Combobox de Entidades Fuertes
    private void llenarcbx(){
        
        for(int i=0; i<Entidades.size(); i++)
        {
            cbxEntidad1.addItem(Entidades.get(i).Nombre);
            cbxEntidad2.addItem(Entidades.get(i).Nombre);
        }
        //Para llenar el combobox (Utilizalo con un for para llenarlo ya que empiza vacio)
        //Seria un mismo for solo que con una linea extra para el segundo y meterle lo mismo
    
    }
    
    //Funcion que crea y extrae los datos de los elementos de la ventana
    private void Crear(){
        
        int i=0;
        char SelCard = 'N';
        int SelPart = 0;
        ArrayList<Atributo> RelAtribs = new ArrayList<Atributo>();
        ArrayList<Entidad> Select = new ArrayList<Entidad>();
        
        Select.add(Entidades.get(cbxEntidad1.getSelectedIndex()));
        Select.add(Entidades.get(cbxEntidad2.getSelectedIndex()));
        
        for(i=0; i<listA.getSize(); i++){
            System.out.println(""+listA.getElementAt(i)); //Donde listA.getElementAt(i) es la cadena en el espacio 'i' de la lista
            Atributo NewAtrib = new Atributo(listA.getElementAt(i).toString(), false, false);
            RelAtribs.add(NewAtrib);
        }
        
        System.out.println("Ing");
        if(rbtn11.isSelected())
        {
            SelCard='-';
            System.out.println("Ing -");
            if(rbtntp.isSelected())
            {
                System.out.println("Ing 1");
                SelPart=1;
            }
            else if(rbtnpt.isSelected() == true)
            {
                System.out.println("Ing 2");    
                SelPart=2;
            }
            else
            {
                System.out.println("Ing 3");
                SelPart=3;
            }
                
        }
        if(rbtn1n.isSelected()==true)
        {
            System.out.println("Ing <");
            SelCard='<';
        }
        if(rbtnn1.isSelected()==true)
        {
            System.out.println("Ing >");
            SelCard='>';
        }
        if(rbtnnm.isSelected()==true)
        {
            System.out.println("Ing =");
            SelCard='=';
        }
        for(int x=0; x<AtribComp.size(); x++)
        {
            for(int y=0; y<AtribComp.get(x).Atribs.size(); y++)
            {
                RelAtribs.add(AtribComp.get(x).Atribs.get(y));
            }
        }
        
        Relacion NewRel = new Relacion(txtNombre.getText(), SelCard, SelPart, Select, RelAtribs);
        Relaciones.add(NewRel);
        AtribComp.clear();
    
    }
    
    private void CrearCompuesto(){
            
        ArrayList<Atributo> AtribsC = new ArrayList<Atributo>();
        
        for(int i=0; i<listC.getSize(); i++)
        {
            Atributo NewAtribC = new Atributo(listC.getElementAt(i).toString(), false, false);
            AtribsC.add(NewAtribC);
        }
        
        Entidad Comp = new Entidad(txtNombre.getText(), 'N', 'N', null, false, AtribsC);
        AtribComp.add(Comp);
    
    }
    
    private void EliminarCompuesto(int Ind){ 
        AtribComp.remove(AtribComp.get(Ind));
    }
    
    private void PermisoCC(){
    
        if(txtNombreC.getText().length()==0 || listC.size()<2)
            btnCrearCom.setEnabled(false); //Habilita el boton de Crear
        else
            btnCrearCom.setEnabled(true); //Inhabilita el boton de Crear
    
    }
    
    //Funcion que elimna la entidad seleccionada en la lista de entidades
    private void Eliminar(int Ind){ //Vas a tener la cadena de la entidad que se quiere eliminar
        Relaciones.remove(Relaciones.get(Ind));
    }
    
    //Accion al presionar el boton "Siguiente"
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        ArrayList<Atributo> RelAtribs = new ArrayList<Atributo>();
        for(int i=0; i<Relaciones.size(); i++)
        {
            if(Relaciones.get(i).Card=='-')
            {
                System.out.println("Ext -");
                if(Relaciones.get(i).Part==1)
                {
                    System.out.println("Ext 1");
                    AgregarFK(Relaciones.get(i).Entidades.get(0), Relaciones.get(i).Entidades.get(1), Relaciones.get(i));
                }
                if(Relaciones.get(i).Part==2)
                {
                    System.out.println("Ext 2");
                    AgregarFK(Relaciones.get(i).Entidades.get(1), Relaciones.get(i).Entidades.get(0), Relaciones.get(i));
                }
                if(Relaciones.get(i).Part==3)
                {
                    System.out.println("Ext 3");
                    if(Relaciones.get(i).Entidades.get(0).Tipo==Relaciones.get(i).Entidades.get(1).Tipo || Relaciones.get(i).Entidades.get(0).Tipo == 'D')
                        AgregarFK(Relaciones.get(i).Entidades.get(0), Relaciones.get(i).Entidades.get(1), Relaciones.get(i));
                    else
                        AgregarFK(Relaciones.get(i).Entidades.get(1), Relaciones.get(i).Entidades.get(0), Relaciones.get(i));
                }
            }
            if(Relaciones.get(i).Card=='<')
                AgregarFK(Relaciones.get(i).Entidades.get(1), Relaciones.get(i).Entidades.get(0), Relaciones.get(i));
            if(Relaciones.get(i).Card=='>')
                AgregarFK(Relaciones.get(i).Entidades.get(0), Relaciones.get(i).Entidades.get(1), Relaciones.get(i));
            if(Relaciones.get(i).Card=='=')
            {
                for(int j=0; j<Relaciones.get(i).Entidades.size(); j++)
                {
                    for(int k=0; k<Relaciones.get(i).Entidades.get(j).Atribs.size(); k++)
                    {
                        if(Relaciones.get(i).Entidades.get(j).Atribs.get(k).Pri)
                        {
                            RelAtribs.add(Relaciones.get(i).Entidades.get(j).Atribs.get(k));
                        }
                    }
                }
                for(int l=0; l<Relaciones.get(i).Atribs.size(); l++)
                {
                    Atributo NewAtri = new Atributo(Relaciones.get(i).Atribs.get(l).Nombre, false, false);
                    RelAtribs.add(NewAtri);
                }
                Entidad NewEnt = new Entidad(Relaciones.get(i).Nombre , 'N', 'N', null, true, RelAtribs);
                Entidades.add(NewEnt);
            }
        }
        
        Ventana5 v5 = new Ventana5(); //Se crea un objeto ventana
        
        for(int i=0; i<Entidades.size(); i++)
        {
            System.out.print(Entidades.get(i).Nombre+" = { ");
            for(int j=0; j<Entidades.get(i).Atribs.size(); j++)
            {
                if(Entidades.get(i).Atribs.get(j).Pri && Entidades.get(i).Atribs.get(j).For)
                    System.out.print("°PF°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else if(Entidades.get(i).Atribs.get(j).Pri)
                    System.out.print("°P°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else if(Entidades.get(i).Atribs.get(j).For)
                    System.out.print("°F°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else
                    System.out.print(Entidades.get(i).Atribs.get(j).Nombre+", ");
            }
            System.out.println("}");
        }
        System.out.println("");
        v5.Relaciones(Entidades);
        
        v5.show(); //Muestra el objeto ventana
        dispose(); //Cierra la ventana actual
    }//GEN-LAST:event_btnSiguienteActionPerformed

    //Funcion que recibe una entidad (EntFK) a la que se le va agregar la llave primaria de una segunda entidad (EntPK) y los atributos de la relacion que las une
    private void AgregarFK(Entidad EntFK, Entidad EntPK, Relacion Rel)
    {
        boolean FK=false; //Bandera de existencia de llave foranea
        boolean PK=false; //Bandera que ve si existe la llave primaria de EntPk en EntFK
        for(int j=0; j<EntPK.Atribs.size(); j++) //Revisamos todos los atributos de EntPK
        {
            if(EntPK.Atribs.get(j).Pri) //Si el atributo revisado es una llave primaria
            {
                for(int k=0; k<EntFK.Atribs.size(); k++) //Revisamos todos los atributos de EntFK
                {
                    if(EntFK.Atribs.get(k).For) //Si el atributo revisado es una llave foranea
                    {
                        FK=true; //Levantamos la bandera que nos indica que en EntFK existe al menos una llave foranea
                        if(EntPK.Atribs.get(j).Nombre==EntFK.Atribs.get(k).Nombre) //Si la llave primaria que estamos revisando en EntPK es igual la llave foranea de EntFK que estamos revisando...
                            PK=true;                                   //y la agregamos a los atributos de EntFK
                    }
                }
                if(!FK || !PK) //Si EntFK no tiene ninguna llave foranea...
                {
                    Atributo NewFK = new Atributo(EntPK.Atribs.get(j).Nombre, false, true); //Creamos un nuevo atributo, que sera una llave foranea, con el nombre de la llave primaria en turno...
                    EntFK.Atribs.add(NewFK);                                                //y la agregamos a los atributos de EntFK
                }
                FK=false; //Regresamos la bandera a falso para que no obstruya posibles operaciones con multiples llaves primarias en EntPK
                for(int i=0; i<Rel.Atribs.size(); i++) //En cualquiera de los casos, agregamos los atributos de la relacion a EntFK
                {
                    Atributo NewFK = new Atributo(Rel.Atribs.get(i).Nombre, false, false); //Creamos un nuevo atributo simple con el nombre del atributo de la relacion en turno...
                    EntFK.Atribs.add(NewFK);                                               //y la agregamos a los atributos de EntFK
                }
            }
        }
    }
    
    //Accion al presionar el boton "Introducir Atributo"
    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed
        
        chbxDerivado.setSelected(false);
        listA.addElement(txtAtributos.getText()); //Agrega el valor en el campo de Atributo a la lista
        txtAtributos.setText(""); //Limpia el campo de Atributo
        btnIntroducir.setEnabled(false); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_btnIntroducirActionPerformed

    //Accion al presionar el boton "Eliminar Atributo"
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        listA.removeElementAt(lstAtributos.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar.setEnabled(false); //Inhabilita el boton de Eliminar
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    //Accion al seleccionar un elemento de la lista de atributos
    private void lstAtributosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributosMouseClicked
        
        if(lstAtributos.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar.setEnabled(true); //Habilita el boton de Eliminar
        
    }//GEN-LAST:event_lstAtributosMouseClicked

    //Accion al escribir o borrar caracteres en el campo de Atributos
    private void txtAtributosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtributosKeyTyped
        
        if(txtAtributos.getText().length()==0) //Revisa que el campo de texto de Atributo no esté vacio
            btnIntroducir.setEnabled(false); //Habilita el boton de Introducir
        else
            btnIntroducir.setEnabled(true); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_txtAtributosKeyTyped

    //Accion al presionar el boton "Crear Relacion"
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        Crear(); //Se llama a la funcion que extraera y creara la entidad con todos los datos
        
        //Se reestablecen los valores originales de los elementos de la ventana
        listB.addElement(txtNombre.getText());
        listA.clear();
        listC.clear();
        listD.clear();
        cbxEntidad1.setSelectedIndex(0); 
        cbxEntidad2.setSelectedIndex(0);
        txtNombre.setText("");
        txtAtributos.setText("");
        txtNombreC.setText("");
        txtAtributos2.setText("");
        chbxDerivado.setSelected(false);
        rbtn11.setSelected(true);
        btnCrear.setEnabled(false);
        PermisoCC();
        
    }//GEN-LAST:event_btnCrearActionPerformed

    //Accion al cambiar el estado del radiobutton "1:1", ya sea seleccionar o deseleccionar
    private void rbtn11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtn11StateChanged
       
        //Revisa si el radiobutton esta seleccionado
        if(rbtn11.isSelected()){
        
            //Habilita las opciones de participacion
            rbtntt.setEnabled(true); rbtnpp.setSelected(true);
            rbtnpp.setEnabled(true);
            rbtntp.setEnabled(true);
            rbtnpt.setEnabled(true);
            jPanel5.setEnabled(true);
            
        }else{
            
            //Inhabilita las opciones de participacion
            rbtntt.setEnabled(false); 
            rbtnpp.setEnabled(false); 
            rbtntp.setEnabled(false); 
            rbtnpt.setEnabled(false); 
            jPanel5.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_rbtn11StateChanged

    //Accion al seleccionar un elemento de la lista de entidades
    private void lstProgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProgMouseClicked

        if(lstProg.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminarP.setEnabled(true); //Habilita el boton de Eliminar Entidad

    }//GEN-LAST:event_lstProgMouseClicked

    //Accion al presionar el boton "Eliminar Relacion"
    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed

        Eliminar(lstProg.getSelectedIndex()); //Llama la funcion que borra la entidad de los datos
        listB.removeElementAt(lstProg.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminarP.setEnabled(false); //Inhabilita el boton de Eliminar

    }//GEN-LAST:event_btnEliminarPActionPerformed

    //Accion al escribir o borrar caracteres en el campo de Nombre
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        //Revisa si hay una cadena en el campo de nombre
        if(txtNombre.getText().length()==0)
            btnCrear.setEnabled(false); //Habilita el boton de Crear
        else
            btnCrear.setEnabled(true); //Inhabilita el boton de Crear

    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnIntroducir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducir2ActionPerformed
        
        listC.addElement(txtAtributos2.getText()); //Agrega el valor en el campo de Atributo a la lista
        txtAtributos2.setText(""); //Limpia el campo de Atributo
        btnIntroducir2.setEnabled(false); //Inhabilita el boton de Introducir
        PermisoCC();
        
    }//GEN-LAST:event_btnIntroducir2ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        
        listC.removeElementAt(lstAtributos2.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar2.setEnabled(false); //Inhabilita el boton de Eliminar
        PermisoCC();
        
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void txtAtributos2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtributos2KeyTyped
        
        if(txtAtributos2.getText().length()==0) //Revisa que el campo de texto de Atributo no esté vacio
            btnIntroducir2.setEnabled(false); //Habilita el boton de Introducir
        else
            btnIntroducir2.setEnabled(true); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_txtAtributos2KeyTyped

    private void lstAtributos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributos2MouseClicked
        
        if(lstAtributos2.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar2.setEnabled(true); //Habilita el boton de Eliminar
        
    }//GEN-LAST:event_lstAtributos2MouseClicked

    private void txtNombreCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCKeyTyped
        
        PermisoCC();
        
    }//GEN-LAST:event_txtNombreCKeyTyped

    private void btnCrearComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearComActionPerformed
        
        CrearCompuesto(); //Se llama a la funcion que extraera y creara el atributo con todos los datos

        //Se reestablecen los valores originales de los elementos de la ventana
        listC.clear();
        listD.addElement(txtNombreC.getText());
        txtNombreC.setText("");
        txtAtributos2.setText("");
        PermisoCC(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_btnCrearComActionPerformed

    private void lstProg2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProg2MouseClicked
        
        if(lstProg2.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminarP2.setEnabled(true); //Habilita el boton de Eliminar Entidad
        
    }//GEN-LAST:event_lstProg2MouseClicked

    private void btnEliminarP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarP2ActionPerformed
        
        EliminarCompuesto(lstProg2.getSelectedIndex()); //Llama la funcion que borra la entidad de los datos
        listD.removeElementAt(lstProg2.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminarP2.setEnabled(false); //Inhabilita el boton de Eliminar
        
    }//GEN-LAST:event_btnEliminarP2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCrearCom;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnEliminarP2;
    private javax.swing.JButton btnIntroducir;
    private javax.swing.JButton btnIntroducir2;
    private javax.swing.ButtonGroup btnParticipacion;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup btngCardinalidad;
    private javax.swing.JComboBox<String> cbxEntidad1;
    private javax.swing.JComboBox<String> cbxEntidad2;
    private javax.swing.JCheckBox chbxDerivado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jspAtributos;
    private javax.swing.JScrollPane jspRelaciones;
    private javax.swing.JList<String> lstAtributos;
    private javax.swing.JList<String> lstAtributos2;
    private javax.swing.JList<String> lstProg;
    private javax.swing.JList<String> lstProg2;
    private javax.swing.JRadioButton rbtn11;
    private javax.swing.JRadioButton rbtn1n;
    private javax.swing.JRadioButton rbtnn1;
    private javax.swing.JRadioButton rbtnnm;
    private javax.swing.JRadioButton rbtnpp;
    private javax.swing.JRadioButton rbtnpt;
    private javax.swing.JRadioButton rbtntp;
    private javax.swing.JRadioButton rbtntt;
    private javax.swing.JTextField txtAtributos;
    private javax.swing.JTextField txtAtributos2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreC;
    // End of variables declaration//GEN-END:variables
}
