
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rodri
 */
public class Compuestos extends javax.swing.JFrame {
    
    ArrayList<Entidad> Entidades = new ArrayList<Entidad>();
    ArrayList<Entidad> AtribComp = new ArrayList<Entidad>();
    int TamAnt;

    /**
     * Creates new form Compuestos
     */
    DefaultListModel listA = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listB = new DefaultListModel(); //Se declara un modelo de lista
    public Compuestos() {
        initComponents();
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        btnIntroducir.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnEliminarP.setEnabled(false);
        lstAtributos.setModel(listA);
        lstProg.setModel(listB);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbxEntidad = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txtAtributos = new javax.swing.JTextField();
        btnIntroducir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jspAtributos = new javax.swing.JScrollPane();
        lstAtributos = new javax.swing.JList<>();
        btnCrear = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jspEntidades = new javax.swing.JScrollPane();
        lstProg = new javax.swing.JList<>();
        btnEliminarP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atributos Compuestos");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidad a que Pertenece"));

        cbxEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos que lo Componen"));

        txtAtributos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAtributosKeyTyped(evt);
            }
        });

        btnIntroducir.setText("Introducir Atributo");
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Atributo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lstAtributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributosMouseClicked(evt);
            }
        });
        jspAtributos.setViewportView(lstAtributos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAtributos)
                    .addComponent(btnIntroducir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addComponent(jspAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrear.setText("Crear Atributo");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnSiguiente.setLabel("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos C Creados"));

        lstProg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProgMouseClicked(evt);
            }
        });
        jspEntidades.setViewportView(lstProg);

        btnEliminarP.setText("Eliminar Atributo");
        btnEliminarP.setToolTipText("");
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEliminarP, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarP)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnSiguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Funcion que crea y extrae los datos de los elementos de la ventana
    private void Crear(){
        
        ArrayList<Atributo> Atribs = new ArrayList<Atributo>();
        
        for(int i=0; i<listA.getSize(); i++)
        {
            Atributo NewAtrib = new Atributo(listA.getElementAt(i).toString(), false, false);
            Atribs.add(NewAtrib);
        }
        
        Entidad NewEnt = new Entidad(txtNombre.getText(), 'N', 'N', Entidades.get(cbxEntidad.getSelectedIndex()), false, Atribs);
        AtribComp.add(NewEnt);
        
    }
    
    public void Relaciones(ArrayList<Entidad> Debiles){
        TamAnt = Debiles.size();
        Entidades = (ArrayList) Debiles.clone();
        llenarcbx(); //Se encarga de llenar el Combobox de Entidades
    }
    
    //Se encarga de llenar el Combobox de Entidades Fuertes
    private void llenarcbx(){
        
        for(int i=0; i<Entidades.size(); i++)
        {
            cbxEntidad.addItem(Entidades.get(i).Nombre); 
        }
        //Para llenar el combobox (Utilizalo con un for para llenarlo ya que empiza vacio)
    }
    
    //Funcion que elimna la entidad seleccionada en la lista de entidades
    private void Eliminar(int Ind){ //Vas a tener la cadena de la entidad que se quiere eliminar
        AtribComp.remove(AtribComp.get(Ind));
    }
    
    //Funcion que evalua ciertas condiciones para habilitar o inhabilitar el boton de Crear
    private void permisoCrear(){
    
        //Revisa que los campos de texto de Nombre y Llave primaria no esten vacios ademas de que la lista de atributos no esté vacia
        if(txtNombre.getText().length()==0 || listA.size()<2)
            btnCrear.setEnabled(false); //Habilita el boton de Crear
        else
            btnCrear.setEnabled(true); //Inhabilita el boton de Crear
    
    }
    
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana

    }//GEN-LAST:event_txtNombreKeyTyped

    
    private void txtAtributosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtributosKeyTyped

        if(txtAtributos.getText().length()==0) //Revisa que el campo de texto de Atributo no esté vacio
        btnIntroducir.setEnabled(false); //Habilita el boton de Introducir
        else
        btnIntroducir.setEnabled(true); //Inhabilita el boton de Introducir

    }//GEN-LAST:event_txtAtributosKeyTyped

    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed

        listA.addElement(txtAtributos.getText()); //Agrega el valor en el campo de Atributo a la lista
        txtAtributos.setText(""); //Limpia el campo de Atributo
        btnIntroducir.setEnabled(false); //Inhabilita el boton de Introducir
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana

    }//GEN-LAST:event_btnIntroducirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        listA.removeElementAt(lstAtributos.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar.setEnabled(false);//Inhabilita el boton de Eliminar
        permisoCrear();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void lstAtributosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributosMouseClicked

        if(lstAtributos.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar.setEnabled(true); //Habilita el boton de Eliminar

    }//GEN-LAST:event_lstAtributosMouseClicked

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        Crear(); //Se llama a la funcion que extraera y creara el atributo con todos los datos

        //Se reestablecen los valores originales de los elementos de la ventana
        listA.clear();
        cbxEntidad.setSelectedIndex(0);
        listB.addElement(txtNombre.getText());
        txtNombre.setText("");
        txtAtributos.setText("");
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        for(int i=0; i<AtribComp.size(); i++)
        {
            for(int j=0; j<AtribComp.get(i).Atribs.size(); j++)
            {
                Entidades.get(Entidades.indexOf(AtribComp.get(i).Padre)).Atribs.add(AtribComp.get(i).Atribs.get(j));
            }
        }
        
        Ventana4 v4 = new Ventana4(); //Se crea un objeto ventana
        
        for(int i=0; i<Entidades.size(); i++)
        {
            System.out.print(Entidades.get(i).Nombre+" = { ");
            for(int j=0; j<Entidades.get(i).Atribs.size(); j++)
            {
                if(Entidades.get(i).Atribs.get(j).Pri && Entidades.get(i).Atribs.get(j).For)
                    System.out.print("°PF°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else if(Entidades.get(i).Atribs.get(j).Pri)
                    System.out.print("°P°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else if(Entidades.get(i).Atribs.get(j).For)
                    System.out.print("°F°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else
                    System.out.print(Entidades.get(i).Atribs.get(j).Nombre+", ");
            }
            System.out.println("}");
        }
        System.out.println("");
        v4.Relaciones(Entidades);
        
        v4.show(); //Muestra el objeto ventana
        dispose(); //Cierra la ventana actual

    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void lstProgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProgMouseClicked

        if(lstProg.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminarP.setEnabled(true); //Habilita el boton de Eliminar Entidad

    }//GEN-LAST:event_lstProgMouseClicked

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed

        Eliminar(lstProg.getSelectedIndex()); //Llama la funcion que borra la entidad de los datos
        listB.removeElementAt(lstProg.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminarP.setEnabled(false); //Inhabilita el boton de Eliminar
        if(listB.isEmpty())
        btnSiguiente.setEnabled(false);

    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void cbxEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEntidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compuestos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compuestos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnIntroducir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbxEntidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jspAtributos;
    private javax.swing.JScrollPane jspEntidades;
    private javax.swing.JList<String> lstAtributos;
    private javax.swing.JList<String> lstProg;
    private javax.swing.JTextField txtAtributos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
