
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rodri
 */
public class Ventana3 extends javax.swing.JFrame {
    
    ArrayList<Entidad> Hijas = new ArrayList<Entidad>();
    int TamAnt;
    char SelEsp;

    /**
     * Creates new form Ventana3
     */
    DefaultListModel listA = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listB = new DefaultListModel(); //Se declara un modelo de lista
    
    public Ventana3() {
        //Se inicializan los elementos de la ventana
        initComponents();
        llenarcbx(); //Se encarga de llenar el Combobox de Entidades Fuertes
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        btnIntroducir.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnEliminarP1.setEnabled(false);
        rbtnTotal.setSelected(true);
        rbtnDis.setSelected(true);
        lstAtributos.setModel(listA);
        lstProg1.setModel(listB);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Especializacion = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbxEntidad = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txtAtributos = new javax.swing.JTextField();
        btnIntroducir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jspAtributos = new javax.swing.JScrollPane();
        lstAtributos = new javax.swing.JList<>();
        chbxDerivado = new javax.swing.JCheckBox();
        btnCrear = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jspEntidades1 = new javax.swing.JScrollPane();
        lstProg1 = new javax.swing.JList<>();
        btnEliminarP1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        rbtnDis = new javax.swing.JRadioButton();
        rbtnTras = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rbtnTotal = new javax.swing.JRadioButton();
        rbtnParcial = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entidades Hijas");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidad Padre"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos Simples y Derivados"));

        txtAtributos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAtributosKeyTyped(evt);
            }
        });

        btnIntroducir.setText("Introducir Atributo");
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Atributo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lstAtributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributosMouseClicked(evt);
            }
        });
        jspAtributos.setViewportView(lstAtributos);

        chbxDerivado.setText("Derivado");
        chbxDerivado.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAtributos)
                        .addComponent(btnIntroducir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(chbxDerivado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbxDerivado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrear.setText("Crear Entidad");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnSiguiente.setLabel("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidades Creadas"));

        lstProg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProg1MouseClicked(evt);
            }
        });
        jspEntidades1.setViewportView(lstProg1);

        btnEliminarP1.setText("Eliminar Entidad");
        btnEliminarP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarP1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspEntidades1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspEntidades1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarP1)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Especializacion"));

        Especializacion.add(rbtnDis);
        rbtnDis.setText("Disyuncion");

        Especializacion.add(rbtnTras);
        rbtnTras.setText("Traslape");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnDis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(rbtnTras)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnDis)
                    .addComponent(rbtnTras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Restriccion"));

        buttonGroup1.add(rbtnTotal);
        rbtnTotal.setText("Total");
        rbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTotalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnParcial);
        rbtnParcial.setText("Parcial");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnParcial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTotal)
                    .addComponent(rbtnParcial))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSiguiente))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Relaciones(ArrayList<Entidad> Debiles){
        TamAnt = Debiles.size();
        Hijas = (ArrayList) Debiles.clone();
        llenarcbx(); //Se encarga de llenar el Combobox de Entidades
    }
    
    //Se encarga de llenar el Combobox de Entidades Fuertes
    private void llenarcbx(){
        
        for(int i=0; i<Hijas.size(); i++)
        {
            cbxEntidad.addItem(Hijas.get(i).Nombre); 
        }
        //Para llenar el combobox (Utilizalo con un for para llenarlo ya que empiza vacio)
    
    }
    
    //Funcion que crea y extrae los datos de los elementos de la ventana
    private void Crear(){
        
        int i=0;
        ArrayList<Atributo> HijAtribs = new ArrayList<Atributo>();
        
        rbtnDis.isSelected();
        rbtnTras.isSelected();
        
        cbxEntidad.getSelectedItem(); //Regresa la cadena del elemento seleccionado del combobox
        txtNombre.getText(); //Regresa la cadena del campo de Nombre
        listA.isEmpty(); //Te dice si la lista está vacia (Regresa un valor booleano)
        
        for(int k=0; k<Hijas.get(cbxEntidad.getSelectedIndex()).Atribs.size(); k++)
        {
            if(Hijas.get(cbxEntidad.getSelectedIndex()).Atribs.get(k).Pri)
            {
                Atributo NewPF = new Atributo(Hijas.get(cbxEntidad.getSelectedIndex()).Atribs.get(k).Nombre, true, true);
                HijAtribs.add(NewPF);
            }
        }
        
        
        for(i=0; i<listA.getSize(); i++){
            System.out.println(""+listA.getElementAt(i)); //Donde listA.getElementAt(i) es la cadena en el espacio 'i' de la lista
            Atributo NewAtrib = new Atributo(listA.getElementAt(i).toString(), false, false);
            HijAtribs.add(NewAtrib);
        }
    
        if(rbtnDis.isSelected())
            SelEsp = 'D';
        if(rbtnTras.isSelected())
            SelEsp = 'T';
        
        Entidad NewEnt = new Entidad(txtNombre.getText()+"_"+Hijas.get(cbxEntidad.getSelectedIndex()).Nombre, 'H', SelEsp, Hijas.get(cbxEntidad.getSelectedIndex()),false, HijAtribs);
        Hijas.add(NewEnt);
        
    }
    
    //Funcion que elimna la entidad seleccionada en la lista de entidades
    private void Eliminar(int Ind){ //Vas a tener la cadena de la entidad que se quiere eliminar
       Hijas.remove(Hijas.get(Ind+TamAnt));
    }
    
    //Funcion que evalua ciertas condiciones para habilitar o inhabilitar el boton de Crear
    private void permisoCrear(){
    
        //Revisa que el campo de texto de Nombre no esté vacio
        if(txtNombre.getText().length()==0)
            btnCrear.setEnabled(false); //Habilita el boton de Crear
        else
            btnCrear.setEnabled(true); //Inhabilita el boton de Crear
    
    }
    
    //Accion al presionar el boton "Siguiente"
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        Compuestos comp = new Compuestos(); //Se crea un objeto ventana
        
        for(int i=0; i<Hijas.size(); i++)
        {
            System.out.print(Hijas.get(i).Nombre+" = { ");
            for(int j=0; j<Hijas.get(i).Atribs.size(); j++)
            {
                if(Hijas.get(i).Atribs.get(j).Pri && Hijas.get(i).Atribs.get(j).For)
                    System.out.print("°PF°"+Hijas.get(i).Atribs.get(j).Nombre+", ");
                else if(Hijas.get(i).Atribs.get(j).Pri)
                    System.out.print("°P°"+Hijas.get(i).Atribs.get(j).Nombre+", ");
                else
                    System.out.print(Hijas.get(i).Atribs.get(j).Nombre+", ");
            }
            System.out.println("}");
        }
        System.out.println("");
        comp.Relaciones(Hijas);
        
        comp.show(); //Muestra el objeto ventana
        dispose(); //Cierra la ventana actual
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    //Accion al presionar el boton "Introducir Atributo"
    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed

        chbxDerivado.setSelected(false);        
        listA.addElement(txtAtributos.getText()); //Agrega el valor en el campo de Atributo a la lista
        txtAtributos.setText(""); //Limpia el campo de Atributo
        btnIntroducir.setEnabled(false); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_btnIntroducirActionPerformed

    //Accion al presionar el boton "Eliminar Atributo"
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        listA.removeElementAt(lstAtributos.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar.setEnabled(false); //Inhabilita el boton de Eliminar
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    //Accion al seleccionar un elemento de la lista de atributos
    private void lstAtributosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributosMouseClicked
       
        if(lstAtributos.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar.setEnabled(true); //Habilita el boton de Eliminar
        
    }//GEN-LAST:event_lstAtributosMouseClicked

    //Accion al escribir o borrar caracteres en el campo de Atributos
    private void txtAtributosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtributosKeyTyped
        
        if(txtAtributos.getText().length()==0) //Revisa que el campo de texto de Atributo no esté vacio
            btnIntroducir.setEnabled(false); //Habilita el boton de Introducir
        else
            btnIntroducir.setEnabled(true); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_txtAtributosKeyTyped

    //Accion al escribir o borrar caracteres en el campo de Nombre
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_txtNombreKeyTyped

    //Accion al presionar el boton "Crear Entidad"
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        Crear(); //Se llama a la funcion que extraera y creara la entidad con todos los datos
        
        //Se reestablecen los valores originales de los elementos de la ventana
        listB.addElement(txtNombre.getText());
        rbtnDis.setSelected(true);
        rbtnTotal.setSelected(true);
        chbxDerivado.setSelected(false);
        listA.clear();
        txtNombre.setText("");
        txtAtributos.setText("");
        cbxEntidad.setSelectedIndex(0);
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void lstProg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProg1MouseClicked

        if(lstProg1.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminarP1.setEnabled(true); //Habilita el boton de Eliminar Entidad

    }//GEN-LAST:event_lstProg1MouseClicked

    //Accion al presionar el boton "Eliminar Entidad"
    private void btnEliminarP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarP1ActionPerformed

        Eliminar(lstProg1.getSelectedIndex()); //Llama la funcion que borra la entidad de los datos
        listB.removeElementAt(lstProg1.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminarP1.setEnabled(false); //Inhabilita el boton de Eliminar

    }//GEN-LAST:event_btnEliminarP1ActionPerformed

    private void rbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Especializacion;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarP1;
    private javax.swing.JButton btnIntroducir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxEntidad;
    private javax.swing.JCheckBox chbxDerivado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jspAtributos;
    private javax.swing.JScrollPane jspEntidades1;
    private javax.swing.JList<String> lstAtributos;
    private javax.swing.JList<String> lstProg1;
    private javax.swing.JRadioButton rbtnDis;
    private javax.swing.JRadioButton rbtnParcial;
    private javax.swing.JRadioButton rbtnTotal;
    private javax.swing.JRadioButton rbtnTras;
    private javax.swing.JTextField txtAtributos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
