
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rodri
 */
public class Ventana5 extends javax.swing.JFrame {
    
    int TamAnt;
    ArrayList<Entidad> Entidades = new ArrayList<Entidad>();
    ArrayList<Entidad> Select = new ArrayList<Entidad>();
    ArrayList<Entidad> AtribComp = new ArrayList<Entidad>();

    /**
     * Creates new form Ventana5
     */
    DefaultListModel listA = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listB = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listE = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listC = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listD = new DefaultListModel(); //Se declara un modelo de lista
    
    public Ventana5() {
        //Se inicializan los elementos de la ventana
        initComponents();
        llenarcbx(); //Se encarga de llenar el Combobox de Entidades
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        btnEliminar.setEnabled(false);
        btnEliminar1.setEnabled(false);
        btnEliminarP.setEnabled(false);
        btnEliminarP2.setEnabled(false);
        btnIntroducir2.setEnabled(false);
        btnEliminar2.setEnabled(false);
        btnCrearCom.setEnabled(false);
        lstEntidades.setModel(listA);
        lstProg.setModel(listB);
        lstAtributos.setModel(listE);
        lstAtributos2.setModel(listC);
        lstProg2.setModel(listD);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnIntroducir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jspEntidad = new javax.swing.JScrollPane();
        lstEntidades = new javax.swing.JList<>();
        cbxEntidad = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jspEntidades = new javax.swing.JScrollPane();
        lstProg = new javax.swing.JList<>();
        btnEliminarP = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtAtributos = new javax.swing.JTextField();
        btnIntroducir1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        jspAtributos = new javax.swing.JScrollPane();
        lstAtributos = new javax.swing.JList<>();
        chbxDerivado = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtNombreC = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        txtAtributos2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAtributos2 = new javax.swing.JList<>();
        btnIntroducir2 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        btnCrearCom = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProg2 = new javax.swing.JList<>();
        btnEliminarP2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relaciones de Grado > 2");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidades que Participan"));

        btnIntroducir.setText("Introducir Entidad");
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Entidad");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lstEntidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEntidadesMouseClicked(evt);
            }
        });
        jspEntidad.setViewportView(lstEntidades);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbxEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrear.setText("Crear Relacion");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnSiguiente.setLabel("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Relaciones Creadas"));

        lstProg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProgMouseClicked(evt);
            }
        });
        jspEntidades.setViewportView(lstProg);

        btnEliminarP.setText("Eliminar Relacion");
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspEntidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarP)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos Simples y Derivados de la Relacion"));

        txtAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtributosActionPerformed(evt);
            }
        });
        txtAtributos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAtributosKeyTyped(evt);
            }
        });

        btnIntroducir1.setText("Introducir Atributo");
        btnIntroducir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducir1ActionPerformed(evt);
            }
        });

        btnEliminar1.setText("Eliminar Atributo");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        lstAtributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributosMouseClicked(evt);
            }
        });
        jspAtributos.setViewportView(lstAtributos);

        chbxDerivado.setText("Derivado");
        chbxDerivado.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEliminar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAtributos)
                        .addComponent(btnIntroducir1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(chbxDerivado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbxDerivado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos Compuestos de la Relacion"));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtNombreC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos que lo Componen"));

        txtAtributos2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAtributos2KeyTyped(evt);
            }
        });

        lstAtributos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributos2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstAtributos2);

        btnIntroducir2.setText("Introducir Atributo");
        btnIntroducir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducir2ActionPerformed(evt);
            }
        });

        btnEliminar2.setText("Eliminar Atributo");
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAtributos2)
                    .addComponent(btnIntroducir2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnEliminar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtAtributos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrearCom.setText("Crear Compuesto");
        btnCrearCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearComActionPerformed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos Compuestos Creados"));

        lstProg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProg2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstProg2);

        btnEliminarP2.setText("Eliminar Compuesto");
        btnEliminarP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminarP2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCrearCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearCom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Se encarga de llenar el Combobox de Entidades Fuertes
    private void llenarcbx(){
        for(int i=0; i<Entidades.size(); i++)
        {
            if(!Entidades.get(i).Relacion)
                cbxEntidad.addItem(Entidades.get(i).Nombre);
        }
    }
    
    //Funcion que crea y extrae los datos de los elementos de la ventana
    private void Crear(){

        ArrayList<Atributo> RelAtribs = new ArrayList<Atributo>();
        
        txtNombre.getText(); //Regresa la cadena del campo de Nombre
        
        for(int i=0; i<Select.size(); i++)
        {
            for(int j=0; j<Select.get(i).Atribs.size(); j++)
            {
                if(Select.get(i).Atribs.get(j).Pri)
                {
                    Atributo NewAtrib = new Atributo(Select.get(i).Atribs.get(j).Nombre, true, true);
                    RelAtribs.add(NewAtrib);
                }
            }
        }
        for(int k=0; k<listE.getSize(); k++){
            Atributo NewAtrib = new Atributo(listE.getElementAt(k).toString(), false, false);
            RelAtribs.add(NewAtrib);
        }
        
        for(int x=0; x<AtribComp.size(); x++)
        {
            for(int y=0; y<AtribComp.get(x).Atribs.size(); y++)
            {
                RelAtribs.add(AtribComp.get(x).Atribs.get(y));
            }
        }
        
        Entidad NewEnt = new Entidad(txtNombre.getText(), 'N', 'N', null, true, RelAtribs);
        Entidades.add(NewEnt);
        Select.clear();
        AtribComp.clear();
    
    }
    
    private void CrearCompuesto(){
            
        ArrayList<Atributo> AtribsC = new ArrayList<Atributo>();
        
        for(int i=0; i<listC.getSize(); i++)
        {
            Atributo NewAtribC = new Atributo(listC.getElementAt(i).toString(), false, false);
            AtribsC.add(NewAtribC);
        }
        
        Entidad Comp = new Entidad(txtNombre.getText(), 'N', 'N', null, false, AtribsC);
        AtribComp.add(Comp);
    
    }
    
    private void EliminarCompuesto(int Ind){ 
        AtribComp.remove(AtribComp.get(Ind));
    }
    
    private void PermisoCC(){
    
        if(txtNombreC.getText().length()==0 || listC.size()<2)
            btnCrearCom.setEnabled(false); //Habilita el boton de Crear
        else
            btnCrearCom.setEnabled(true); //Inhabilita el boton de Crear
    
    }
    
    private void Eliminar(int Ind){ //Vas a tener la cadena de la entidad que se quiere eliminar
       Entidades.remove(Entidades.get(Ind+TamAnt));
    }
    
    //Funcion que elimna la entidad seleccionada en la lista de entidades
    public void Relaciones(ArrayList<Entidad> EntsAnt){
        TamAnt = EntsAnt.size();
        Entidades = (ArrayList) EntsAnt.clone();
        llenarcbx(); //Se encarga de llenar el Combobox de Entidades
    }
    
    //Funcion que evalua ciertas condiciones para habilitar o inhabilitar el boton de Crear
    private void permisoCrear(){
    
        //Revisa que el campo de texto de Nombre no esté vacio y que existan al menos 3 entidades en la lista
        if(txtNombre.getText().length()==0 || listA.size()<3)
            btnCrear.setEnabled(false); //Habilita el boton de Crear
        else
            btnCrear.setEnabled(true); //Inhabilita el boton de Crear
    
    }
    
    //Accion al presionar el boton "Siguiente"
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
       
        Ventana6 v6 = new Ventana6(); //Se crea un objeto ventana
        
        for(int i=0; i<Entidades.size(); i++)
        {
            System.out.print(Entidades.get(i).Nombre+" = { ");
            for(int j=0; j<Entidades.get(i).Atribs.size(); j++)
            {
                if(Entidades.get(i).Atribs.get(j).Pri && Entidades.get(i).Atribs.get(j).For)
                    System.out.print("°PF°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else if(Entidades.get(i).Atribs.get(j).Pri)
                    System.out.print("°P°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else if(Entidades.get(i).Atribs.get(j).For)
                    System.out.print("°F°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else
                    System.out.print(Entidades.get(i).Atribs.get(j).Nombre+", ");
            }
            System.out.println("}");
        }
        System.out.println("");
        v6.Relaciones(Entidades);
        
        v6.show(); //Muestra el objeto ventana
        dispose(); //Cierra la ventana actual
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    //Accion al presionar el boton "Eliminar Entidad"
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        Select.remove(Entidades.get(lstEntidades.getSelectedIndex()));
        
        listA.removeElementAt(lstEntidades.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar.setEnabled(false); //Inhabilita el boton de Eliminar
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    //Accion al presionar el boton "Introducir Entidad"
    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed
        
        listA.addElement(cbxEntidad.getSelectedItem()); //Agrega el valor en el combobox de Entidades a la lista
        
        Select.add(Entidades.get(cbxEntidad.getSelectedIndex()));
        
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_btnIntroducirActionPerformed

    //Accion al seleccionar un elemento de la lista de atributos
    private void lstEntidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEntidadesMouseClicked
        
        if(lstEntidades.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar.setEnabled(true); //Habilita el boton de Eliminar
        
    }//GEN-LAST:event_lstEntidadesMouseClicked

    //Accion al escribir o borrar caracteres en el campo de Nombre
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_txtNombreKeyTyped

    //Accion al presionar el boton "Crear Relacion"
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        Crear(); //Se llama a la funcion que extraera y creara la entidad con todos los datos
        
        //Se reestablecen los valores originales de los elementos de la ventana
        listA.clear();
        listB.addElement(txtNombre.getText());
        listE.clear();
        listC.clear();
        listD.clear();
        chbxDerivado.setSelected(false);
        txtNombre.setText("");
        txtAtributos.setText("");
        txtNombreC.setText("");
        txtAtributos2.setText("");
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        PermisoCC();
        
    }//GEN-LAST:event_btnCrearActionPerformed

    //Accion al seleccionar un elemento de la lista de entidades
    private void lstProgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProgMouseClicked

        if(lstProg.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminarP.setEnabled(true); //Habilita el boton de Eliminar Entidad

    }//GEN-LAST:event_lstProgMouseClicked

    //Accion al presionar el boton "Eliminar Relacion"
    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed

        Eliminar(lstProg.getSelectedIndex()); //Llama la funcion que borra la entidad de los datos
        listB.removeElementAt(lstProg.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminarP.setEnabled(false); //Inhabilita el boton de Eliminar

    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void txtAtributosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtributosKeyTyped

        if(txtAtributos.getText().length()==0) //Revisa que el campo de texto de Atributo no esté vacio
        btnIntroducir1.setEnabled(false); //Habilita el boton de Introducir
        else
        btnIntroducir1.setEnabled(true); //Inhabilita el boton de Introducir

    }//GEN-LAST:event_txtAtributosKeyTyped

    private void btnIntroducir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducir1ActionPerformed

        chbxDerivado.setSelected(false);
        listE.addElement(txtAtributos.getText()); //Agrega el valor en el campo de Atributo a la lista
        txtAtributos.setText(""); //Limpia el campo de Atributo
        btnIntroducir1.setEnabled(false); //Inhabilita el boton de Introducir

    }//GEN-LAST:event_btnIntroducir1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed

        listE.removeElementAt(lstAtributos.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar1.setEnabled(false); //Inhabilita el boton de Eliminar

    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void lstAtributosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributosMouseClicked

        if(lstAtributos.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar1.setEnabled(true); //Habilita el boton de Eliminar

    }//GEN-LAST:event_lstAtributosMouseClicked

    private void txtAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtributosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtributosActionPerformed

    private void btnIntroducir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducir2ActionPerformed
        
        listC.addElement(txtAtributos2.getText()); //Agrega el valor en el campo de Atributo a la lista
        txtAtributos2.setText(""); //Limpia el campo de Atributo
        btnIntroducir2.setEnabled(false); //Inhabilita el boton de Introducir
        PermisoCC();
        
    }//GEN-LAST:event_btnIntroducir2ActionPerformed

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        
        listC.removeElementAt(lstAtributos2.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar2.setEnabled(false); //Inhabilita el boton de Eliminar
        PermisoCC();
        
    }//GEN-LAST:event_btnEliminar2ActionPerformed

    private void lstAtributos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributos2MouseClicked
        
        if(lstAtributos2.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar2.setEnabled(true); //Habilita el boton de Eliminar
        
    }//GEN-LAST:event_lstAtributos2MouseClicked

    private void txtAtributos2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtributos2KeyTyped
        
        if(txtAtributos2.getText().length()==0) //Revisa que el campo de texto de Atributo no esté vacio
            btnIntroducir2.setEnabled(false); //Habilita el boton de Introducir
        else
            btnIntroducir2.setEnabled(true); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_txtAtributos2KeyTyped

    private void txtNombreCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCKeyTyped
        
        PermisoCC();
        
    }//GEN-LAST:event_txtNombreCKeyTyped

    private void btnCrearComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearComActionPerformed
        
        CrearCompuesto(); //Se llama a la funcion que extraera y creara el atributo con todos los datos

        //Se reestablecen los valores originales de los elementos de la ventana
        listC.clear();
        listD.addElement(txtNombreC.getText());
        txtNombreC.setText("");
        txtAtributos2.setText("");
        PermisoCC(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_btnCrearComActionPerformed

    private void lstProg2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProg2MouseClicked
        
        if(lstProg2.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminarP2.setEnabled(true); //Habilita el boton de Eliminar Entidad
        
    }//GEN-LAST:event_lstProg2MouseClicked

    private void btnEliminarP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarP2ActionPerformed
        
        EliminarCompuesto(lstProg2.getSelectedIndex()); //Llama la funcion que borra la entidad de los datos
        listD.removeElementAt(lstProg2.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminarP2.setEnabled(false); //Inhabilita el boton de Eliminar
        
    }//GEN-LAST:event_btnEliminarP2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCrearCom;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnEliminarP2;
    private javax.swing.JButton btnIntroducir;
    private javax.swing.JButton btnIntroducir1;
    private javax.swing.JButton btnIntroducir2;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbxEntidad;
    private javax.swing.JCheckBox chbxDerivado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jspAtributos;
    private javax.swing.JScrollPane jspEntidad;
    private javax.swing.JScrollPane jspEntidades;
    private javax.swing.JList<String> lstAtributos;
    private javax.swing.JList<String> lstAtributos2;
    private javax.swing.JList<String> lstEntidades;
    private javax.swing.JList<String> lstProg;
    private javax.swing.JList<String> lstProg2;
    private javax.swing.JTextField txtAtributos;
    private javax.swing.JTextField txtAtributos2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreC;
    // End of variables declaration//GEN-END:variables
}
