
import javax.swing.DefaultListModel;
import javax.swing.JList;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rodri
 */
public class Ventana1 extends javax.swing.JFrame {
    
    ArrayList<Entidad> Fuertes = new ArrayList<Entidad>(); //Entidades fuertes ingresadas

    /**
     * Creates new form Ventana1
     */
    DefaultListModel listA = new DefaultListModel(); //Se declara un modelo de lista
    DefaultListModel listB = new DefaultListModel(); //Se declara un modelo de lista
    
    public Ventana1() {
        //Se inicializan los elementos de la ventana
        initComponents();
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        btnIntroducir.setEnabled(false); //Inhabilita el boton "Crear"
        btnEliminar.setEnabled(false);
        btnSiguiente.setEnabled(false);
        btnEliminarP.setEnabled(false);
        lstAtributos.setModel(listA);
        lstProg.setModel(listB);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtPK = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtAtributos = new javax.swing.JTextField();
        btnIntroducir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jspAtributos = new javax.swing.JScrollPane();
        lstAtributos = new javax.swing.JList<>();
        chbxDerivado = new javax.swing.JCheckBox();
        btnCrear = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jspEntidades = new javax.swing.JScrollPane();
        lstProg = new javax.swing.JList<>();
        btnEliminarP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entidad Fuerte");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Llave Primaria"));

        txtPK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPKKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPK, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos Simples y Derivados"));

        txtAtributos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAtributosKeyTyped(evt);
            }
        });

        btnIntroducir.setText("Introducir Atributo");
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Atributo");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lstAtributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributosMouseClicked(evt);
            }
        });
        jspAtributos.setViewportView(lstAtributos);

        chbxDerivado.setText("Derivado");
        chbxDerivado.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAtributos)
                        .addComponent(btnIntroducir, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addComponent(chbxDerivado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbxDerivado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntroducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCrear.setText("Crear Entidad");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnSiguiente.setLabel("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidades Creadas"));

        lstProg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProgMouseClicked(evt);
            }
        });
        jspEntidades.setViewportView(lstProg);

        btnEliminarP.setText("Eliminar Entidad");
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEliminarP, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspEntidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarP)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnSiguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Funcion que crea y extrae los datos de los elementos de la ventana
    private void Crear(){
        
        int i=0;
        ArrayList<Atributo> FuerAtribs = new ArrayList<Atributo>(); //Atributos ingresados
        
        txtNombre.getText(); //Regresa la cadena del campo de Nombre
        txtPK.getText(); //Regresa la cadena del campo de Llave Primaria
        
        Atributo NewPK = new Atributo(txtPK.getText(), true, false); //Creamos un nuevo atributo, que sera llave primaria, con el nombre ingresado en el campo "Llave Primaria"...
        FuerAtribs.add(NewPK);                                       //y lo agregamos a los atributos ingresados
        
        for(i=0; i<listA.getSize(); i++){
            System.out.println(""+listA.getElementAt(i)); //Donde listA.getElementAt(i) es la cadena en el espacio 'i' de la lista
            Atributo NewAtrib = new Atributo(listA.getElementAt(i).toString(), false, false); //Creamos un atributo por cada elemento puesto en la lista de "Otros atributos"...
            FuerAtribs.add(NewAtrib);                                                         //y los agregamos en los atributos ingresados
        }
        
        Entidad NewEnt = new Entidad(txtNombre.getText(), 'F', 'N', null, false, FuerAtribs); //Creamos una nueva entidad con el nombre ingresado en el campo "Nombre", sin especializacion, sin entidad padre y con los atributos ingresados...
        Fuertes.add(NewEnt);                                                      //la agregamos a las entidades fuertes ingresadas
        
    }
    
    //Funcion que elimna la entidad seleccionada en la lista de entidades
    private void Eliminar(int Ind){ //Vas a tener la cadena de la entidad que se quiere eliminar
        Fuertes.remove(Fuertes.get(Ind)); //Quitamos la entidad de las entidades fuertes ingresadas de acuerdo al numero de indice qdel elemento seleccionado en la lista de "Entidades Creadas"
    }
    
    //Funcion que evalua ciertas condiciones para habilitar o inhabilitar el boton de Crear
    private void permisoCrear(){
    
        //Revisa que los campos de texto de Nombre y Llave primaria no esten vacios ademas de que la lista de atributos no esté vacia
        if(txtNombre.getText().length()==0 || txtPK.getText().length()==0)
            btnCrear.setEnabled(false); //Habilita el boton de Crear
        else
            btnCrear.setEnabled(true); //Inhabilita el boton de Crear
    
    }
    
    //Accion al presionar el boton "Siguiente"
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        Ventana2 v2 = new Ventana2(); //Se crea un objeto ventana
        
        //impresion de prueba de las entidades hasta este momento
        for(int i=0; i<Fuertes.size(); i++)
        {
            System.out.print(Fuertes.get(i).Nombre+" = { ");
            
            for(int j=0; j<Fuertes.get(i).Atribs.size(); j++)
            {
                if(Fuertes.get(i).Atribs.get(j).Pri)
                    System.out.print("°P°"+Fuertes.get(i).Atribs.get(j).Nombre+", ");
                else
                    System.out.print(Fuertes.get(i).Atribs.get(j).Nombre+", ");
            }
            System.out.println("}");
        }
        System.out.println("");
        v2.Relaciones(Fuertes); //Le pasamos las entidades ingresadas al nuevo objeto ventana para seguir trabajando con ellas
        
        v2.show(); //Muestra el objeto ventana
        dispose(); //Cierra la ventana actual
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    //Accion al presionar el boton "Introducir Atributo"
    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed

        chbxDerivado.setSelected(false);
        listA.addElement(txtAtributos.getText()); //Agrega el valor en el campo de Atributo a la lista
        txtAtributos.setText(""); //Limpia el campo de Atributo
        btnIntroducir.setEnabled(false); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_btnIntroducirActionPerformed

    //Accion al presionar el boton "Eliminar Atributo"
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        listA.removeElementAt(lstAtributos.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminar.setEnabled(false); //Inhabilita el boton de Eliminar
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    //Accion al seleccionar un elemento de la lista de atributos
    private void lstAtributosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributosMouseClicked
        
        if(lstAtributos.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminar.setEnabled(true); //Habilita el boton de Eliminar
        
    }//GEN-LAST:event_lstAtributosMouseClicked

    //Accion al escribir o borrar caracteres en el campo de Atributos
    private void txtAtributosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtributosKeyTyped
        
        if(txtAtributos.getText().length()==0) //Revisa que el campo de texto de Atributo no esté vacio
            btnIntroducir.setEnabled(false); //Habilita el boton de Introducir
        else
            btnIntroducir.setEnabled(true); //Inhabilita el boton de Introducir
        
    }//GEN-LAST:event_txtAtributosKeyTyped

    //Accion al escribir o borrar caracteres en el campo de Nombre
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_txtNombreKeyTyped

    //Accion al escribir o borrar caracteres en el campo de Llave Primaria
    private void txtPKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPKKeyTyped
        
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_txtPKKeyTyped

    //Accion al presionar el boton "Crear Entidad"
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        Crear(); //Se llama a la funcion que extraera y creara la entidad con todos los datos
        
        //Se reestablecen los valores originales de los elementos de la ventana
        btnSiguiente.setEnabled(true);
        listB.addElement(txtNombre.getText());
        listA.clear();
        txtNombre.setText("");
        txtPK.setText("");
        txtAtributos.setText("");
        permisoCrear(); //Se llama a la funcion que evaluara la situacion general de la ventana
        
    }//GEN-LAST:event_btnCrearActionPerformed
    
    //Accion al presionar el boton "Eliminar Entidad"
    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed
        
        Eliminar(lstProg.getSelectedIndex()); //Llama la funcion que borra la entidad de los datos
        listB.removeElementAt(lstProg.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminarP.setEnabled(false); //Inhabilita el boton de Eliminar
        if(listB.isEmpty())
            btnSiguiente.setEnabled(false);
        
    }//GEN-LAST:event_btnEliminarPActionPerformed

    //Accion al seleccionar un elemento de la lista de entidades
    private void lstProgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProgMouseClicked
        
        if(lstProg.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminarP.setEnabled(true); //Habilita el boton de Eliminar Entidad
        
    }//GEN-LAST:event_lstProgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnIntroducir;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JCheckBox chbxDerivado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jspAtributos;
    private javax.swing.JScrollPane jspEntidades;
    private javax.swing.JList<String> lstAtributos;
    private javax.swing.JList<String> lstProg;
    private javax.swing.JTextField txtAtributos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPK;
    // End of variables declaration//GEN-END:variables
}
