
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rodri
 */
public class Ventana6 extends javax.swing.JFrame {

    ArrayList<Entidad> Entidades = new ArrayList<Entidad>();
    int TamAnt;
    
    /**
     * Creates new form Ventana6
     */
    DefaultListModel listA = new DefaultListModel(); //Se declara un modelo de lista
    public Ventana6() {
        //Se inicializan los elementos de la ventana
        initComponents();
        btnCrear.setEnabled(false);
        btnEliminarP.setEnabled(false);
        lstAtributos.setModel(listA);
        llenarcbx(); //Se encarga de llenar el Combobox de Entidades
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbxEntidad = new javax.swing.JComboBox<>();
        btnSiguiente = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jspEntidades = new javax.swing.JScrollPane();
        lstAtributos = new javax.swing.JList<>();
        btnEliminarP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atributos Multivalor");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Entidad a que Pertenece"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSiguiente.setLabel("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnCrear.setText("Agregar Atributo");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos M Creados"));

        lstAtributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAtributosMouseClicked(evt);
            }
        });
        jspEntidades.setViewportView(lstAtributos);

        btnEliminarP.setText("Eliminar Atributo");
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEliminarP, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarP)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnSiguiente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Relaciones(ArrayList<Entidad> EntsAnt){
        TamAnt=EntsAnt.size();
        Entidades = (ArrayList) EntsAnt.clone();
        llenarcbx(); //Se encarga de llenar el Combobox de Entidades
    }
    
    //Se encarga de llenar el Combobox de Entidades Fuertes
    private void llenarcbx(){
        for(int i=0; i<Entidades.size(); i++)
        {
            if(!Entidades.get(i).Relacion)
                cbxEntidad.addItem(Entidades.get(i).Nombre);
        }
    }
    
    //Funcion que crea y extrae los datos de los elementos de la ventana
    private void Crear(){
        
        ArrayList<Atributo> EntAtribs = new ArrayList<Atributo>();
        
        txtNombre.getText(); //Regresa la cadena del campo de Nombre
        cbxEntidad.getSelectedItem(); //Regresa la cadena del elemento seleccionado del combobox
        
        Atributo NewP = new Atributo(txtNombre.getText(), true, false);
        EntAtribs.add(NewP);
        for(int i=0; i<Entidades.get(cbxEntidad.getSelectedIndex()).Atribs.size(); i++)
        {
            if(Entidades.get(cbxEntidad.getSelectedIndex()).Atribs.get(i).Pri)
            {
                Atributo NewPF = new Atributo(Entidades.get(cbxEntidad.getSelectedIndex()).Atribs.get(i).Nombre, true, true);
                EntAtribs.add(NewPF);
            }
        }
        
        Entidad NewEnt = new Entidad(txtNombre.getText()+"_"+Entidades.get(cbxEntidad.getSelectedIndex()).Nombre, 'N', 'N', null, false, EntAtribs);
        Entidades.add(NewEnt);
    
    }
    
    private void Eliminar(int Ind){ //Vas a tener la cadena de la entidad que se quiere eliminar
       Entidades.remove(Entidades.get(Ind+TamAnt));
    }
    
    //Accion al presionar el boton "Siguiente"
    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        Resultado vr = new Resultado(); //Se crea un objeto ventana
        
        for(int i=0; i<Entidades.size(); i++)
        {
            System.out.print(Entidades.get(i).Nombre+" = { ");
            for(int j=0; j<Entidades.get(i).Atribs.size(); j++)
            {
                if(Entidades.get(i).Atribs.get(j).Pri && Entidades.get(i).Atribs.get(j).For)
                    System.out.print("°PF°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else if(Entidades.get(i).Atribs.get(j).Pri)
                    System.out.print("°P°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else if(Entidades.get(i).Atribs.get(j).For)
                    System.out.print("°F°"+Entidades.get(i).Atribs.get(j).Nombre+", ");
                else
                    System.out.print(Entidades.get(i).Atribs.get(j).Nombre+", ");
            }
            System.out.println("}");
        }
        System.out.println("");
        vr.Relaciones(Entidades);
        
        vr.show(); //Muestra el objeto ventana
        dispose(); //Cierra la ventana actual
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    //Accion al escribir o borrar caracteres en el campo de Nombre
    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        
        //Revisa que el campo de texto de Nombre no esté vacio
        if(txtNombre.getText().length()==0)
            btnCrear.setEnabled(false); //Habilita el boton de Agregar
        else
            btnCrear.setEnabled(true); //Inhabilita el boton de Agregar
        
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        Crear(); //Se llama a la funcion que extraera y creara la entidad con todos los datos
        
        //Se reestablecen los valores originales de los elementos de la ventana
        listA.addElement(txtNombre.getText());
        txtNombre.setText("");
        cbxEntidad.setSelectedIndex(0);
        btnCrear.setEnabled(false);
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void lstAtributosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAtributosMouseClicked

        if(lstAtributos.getSelectedIndex()!=-1) //Revisa que se esté seleccionando un elemento valido de la lista
        btnEliminarP.setEnabled(true); //Habilita el boton de Eliminar Entidad

    }//GEN-LAST:event_lstAtributosMouseClicked

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed

        Eliminar(lstAtributos.getSelectedIndex()); //Llama la funcion que borra el atributo de los datos
        listA.removeElementAt(lstAtributos.getSelectedIndex()); //Elimina el elemento seleccionado de la lista
        btnEliminarP.setEnabled(false); //Inhabilita el boton de Eliminar

    }//GEN-LAST:event_btnEliminarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> cbxEntidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jspEntidades;
    private javax.swing.JList<String> lstAtributos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
